### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Unlimited VPN
email: secureconnections.help@gmail.com
description: A fast and secure VPN with free Indian servers and unlimited bandwidth
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unlimitedvpn.tech" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#536DFE'
twitter_username:
github_username:
author: Secure Connections
logo: assets/images/favicon.ico
twitter:
  username:
social:
  name: Unlimited VPN
  links:

languages: ["en"]
ampdir: amp

github:

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
google_analytics: G-1H0RKWB8CB
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
